project:
  output-dir: _site

format:
  html:
    webr:
      workers: true
      service-worker: true
    code-tools: true
    include-in-header:
      - text: |
          <script src="https://webr.r-wasm.org/latest/webr.js"></script>
          <style>
            .run-button {
              background: #4CAF50;
              color: white;
              border: none;
              padding: 5px 10px;
              margin-bottom: 10px;
              border-radius: 4px;
              cursor: pointer;
            }
            .run-button:hover {
              background: #45a049;
            }
          </style>
          <script>
            document.addEventListener('DOMContentLoaded', () => {
              // Initialize WebR
              window.webr = new WebR();
              webr.init();
              
              // Add run buttons to all WebR chunks
              document.querySelectorAll('.webr-code').forEach(el => {
                const button = document.createElement('button');
                button.className = 'run-button';
                button.textContent = 'Run Code';
                button.onclick = () => {
                  const code = el.textContent;
                  webr.evalR(code).then(out => {
                    const outputDiv = document.createElement('div');
                    outputDiv.className = 'webr-output';
                    outputDiv.innerHTML = out.output;
                    el.parentNode.insertBefore(outputDiv, el.nextSibling);
                  });
                };
                el.parentNode.insertBefore(button, el);
              });
            });
          </script>