project:
  output-dir: _site  # Sets output directory for rendered files

format:
  html:
    webr:
      workers: true
      service-worker: true  # Required for session persistence
    code-tools:
      source: true
      toggle: true
    include-in-header:
      - text: |
          <script>
            // Configure interactive WebR environment
            document.addEventListener('DOMContentLoaded', () => {
              window.webr = new WebR({
                interactive: true,  // Enable full interactivity
                stdout: (line) => console.log(line),
                stderr: (line) => console.error(line)
              });
              webr.init();
            });
          </script>
