project:
  output-dir: _site  # Sets output directory for rendered files

format:
  html:
    webr:
      workers: true
      service-worker: true  # Required for persistent sessions
      environment: interactive  # Enable full interactivity
      packages: ["shiny", "DT"]  # For interactive elements
    code-tools: true  # Enable code copy/run buttons
    include-in-header:
      - text: |
          <script>
            // Optional: Configure WebR behavior
            window.WebR = {
              REnv: {
                HOME: '/tmp',
                R_DEFAULT_PACKAGES: 'datasets,utils,grDevices,graphics,stats'
              }
            }
          </script>
